# https://docs.github.com/en/code-security/reference/supply-chain-security/dependabot-options-reference#allow--
#this file should be in .github/dependabot.yml
version: 2
updates:
  - package-ecosystem: "npm" #this creates one PR if groups is being used.
    directory: "/reactviewer" # where the package.json/package-lock.json lives in each module
    schedule:
      interval: "daily" # daily, weekly, monthly, quarterly, semiannually, yearly, or cron
    open-pull-requests-limit: 0 #limit on the maximum number of pull requests for version updates open at any time. Security updates have a separate, internal limit of ten open pull requests, can't be changed.
    groups: # Combines multiple dependency updates into a single pull request
      security-updates: #name of group, can be anything
        applies-to: security-updates #or version-updates
        patterns:
          - "*"
  - package-ecosystem: "maven"
    directory: "/capstone/stone" #where the pom.xml lives in each module
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
    groups:
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"  # e.g "org.springframework*"  groups all spring framework security updates
